[package]
name = "benechico-liroedas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
hex = "0.4.3"
serde = { features = ["derive"]}
serde_json = "1.0"
sha2 = "0.10.0"

